version: "2"
linters:
  default: standard
  enable:
    - misspell
    - gosec
    - asciicheck
    - dupword
    - govet
    - copyloopvar
    - durationcheck
    - errorlint
    - misspell
    - nolintlint
    - perfsprint
    - predeclared
    - unconvert
    - usestdlibvars
    - wastedassign
  exclusions:
    paths:
      - ^.*\.(pb|y)\.go$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - consul-journey
  exclusions:
    paths:
      - ^.*\.(pb|y)\.go$